{% set version = "3.13.1" %}
{% set sha256 = "8da29b72fb56170dd39e3a8ea5074071a8fa63b29346874010b8d293c2f72a3e" %}

package:
  name: spades
  version: {{ version }}

source:
  url: http://cab.spbu.ru/files/release{{ version }}/SPAdes-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - bzip2
    - llvm-openmp # [osx]
    - openmp
  run:
    - llvm-openmp # [osx]
    - openmp
    - python

test:
  commands:
    - spades.py --version
    - rnaspades.py --version
    - truspades.py --version
    - metaspades.py --version
    - plasmidspades.py --version
    - spades.py --test && rm -rf spades_test
    - spades-kmercount -h

about:
  home: http://cab.spbu.ru/software/spades/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: SPAdes (St. Petersburg genome assembler) is intended for both standard isolates and single-cell MDA bacteria assemblies.
  description: |
    SPAdes (St. Petersburg genome assembler) is a genome assembly algorithm which was designed for single cell and
    multi-cells bacterial data sets. However, it might not be suitable for large genomes projects.

    SPAdes works with Ion Torrent, PacBio, Oxford Nanopore, and Illumina paired-end, mate-pairs and single reads
  dev_url: https://github.com/ablab/spades
  doc_url: http://cab.spbu.ru/files/release{{version}}/manual.html
extra:
  recipe-maintainers:
    - druvus
    - notestaff
  identifiers:
    - biotools:Spades
    - doi:10.1089/cmb.2012.0021
    - doi:10.1101/gr.213959.116
